version: '2'
services:
    bidders:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - "5000:5000"
        restart: always
        volumes:
            - .:/bidders