version: '3'  # version of compose format

services:
  bidders:
    build: .  # path is relative to docker-compose.yml localtion
    volumes:
      - .:/usr/src/bidders # mount point
    ports:
      - 5000:5000  # host:container