version: '2'

services:
  auctions:
    container_name: auctions
    build: .
    command: go run main.go
    volumes:
      - .:/go/src/header-bidding
    working_dir: /go/src/header-bidding
    ports:
      - "8000:8000"
